### ISSUE TITLE
Not working on 1.16.4 (forge 35.0.18)

### ISSUE THREAD

**Issue by savvasdalkitsis** [ShadowCooper/TogglePvP#1]
For some reason this isn't working for me. On Minecraft 1.16.4 using Froge 35.0.18.

 

From some troubleshooting i did, the load function isn't called first of all for some bizzare reason but more importantly, the proximity check doesn't move people into the close team when they approach each other.

 

Any ideas?

**Comment by ShadowCooper** [comment]
This is a datapack, not a mod. You can't install it using forge, you simply add it to the datapacks folder on your world. More details in the description of the datapack. It should work once you place it there :D

Edit: Reopened in case you installed it correctly but were just giving your minecraft version...

**Comment by savvasdalkitsis** [comment]
That is indeed the case. I installed it next to my other data packs in the correct folder. :D I should have clarified a bit better.

The other ones work fine so it's not something weird that affects all of them

**Comment by ShadowCooper** [comment]
Does anything work in the datapack? Can you check the flame particles that appear when someone has pvp on? I have a server with my friends and it works fine on there with some other datapacks. I also tested it on a private server with carpet mod bots. Maybe a mod or datapack does something with the teams? Also, note that players are only added to team close when they are on a different team.

**Comment by savvasdalkitsis** [comment]
so I had another datapack that modified teams but made sure to remove that before testing and reset the players' teams.

I realised the load function didn't get called cause the pvpoff and close teams aren't created when i run /reload

I can call `/function togglepvp:load` manually and then the teams will be created but the player particles will not show.

It is the weirdest thing.

Even though the teams get created when i call load manually, proximity doesn't add/remove people from the teams :(

I even tried adding the datapack zip (even tried it unzipped just as a folder) into a new test world that i have set up, without any other datapacks, and it won't load :(

Not sure what i'm doing wrong tbh

I wish there was a way to troubleshoot datapacks so i can provide you with some logs or something

**Comment by savvasdalkitsis** [comment]
Perhaps one of our mods is interfering somehow? I cannot even see the datapack listed when i do `/datapack list` in my test world.

our list of installed mods is here: bitly.com/kevin-nation

I'll try to create a new profile with no mods and see if it works to see if i can narrow it down

**Comment by savvasdalkitsis** [comment]
OK. I created a brand new profile in Curseforge for 1.16. No mods (other than forge obviously), new world, with cheats enabled, even tried opening it up to LAN but it won't load the datapack.

**Comment by savvasdalkitsis** [comment]
Right so i knew i was being an idiot but couldn't figure out what kind of idiot.

The zip contains the folder that needs to go in the datapack, can't add the zip itself. And when i was unzipping it, it would put it inside another folder too so it wouldn't load.

Might be easier to make it so the zip can be dropped as is in the datpacks folder but it works. It was my mistake, apologies

**Comment by ShadowCooper** [comment]
No problem, glad your issue was resolved. I was thinking of making the .zip solely contain the datapack files but I thought that the download explanation in the description would be enough, I might change it later though. Thanks :)
